0DCL EDTNOVW EXT ENTRY             /* EDIT NO VIEW TO CLIENT          */ EDTMAIL
                (CHAR (01),        /* IN  NOVW                        */ EDTMAIL
                 CHAR (01),        /* OUT NOVW (EDITTED)              */ EDTMAIL
                 CHAR (79))        /* OUT EDIT ERROR MESSAGE          */ EDTMAIL
          RETURNS (BIT(1));        /* 0=OK 1=ERROR                    */ EDTMAIL
