 /* PLIINCL ***********************************************************/
 /* STATDAO: DRIVER STATUS DATA ACCESS                                */
 /* OWNING SYSTEM: DSSM - DRIVER LICENCING SYSTEM                     */
 /*********************************************************************/
 /*                                                                   */
 /* WHEN       WHO  CR #     WHAT                                     */
 /* ---------- ---- -------- ---------------------------------------- */
 /* 2006-02-27 NK            ORIGINAL                                 */
 /*********************************************************************/
 DCL STATDAO EXT ENTRY (FIXED BINARY(15,0),
                        FIXED BINARY(31,0),
                        *,
                        *,
                        CHAR(79))
             RETURNS(BIT(1));
 %INCLUDE STATCMD;
